### ISSUE TITLE
PKGBUILD

### ISSUE THREAD

**Issue by Narrat** [yabok/yawa#3]
cmake is missing from makedepends.

And I'm curious. Any specific reasons why this isn't on the AUR?
I almost uploaded one, but I noticed you're active on the AUR and included a PKGBUILD within the repo.

**Comment by HalosGhost** [comment]
yaylabels

**Comment by kyrias** [comment]
@Narrat Thanks for reporting this!

There isn't really any reason it isn't in the AUR. I thought I had uploaded it, but it seems I did not. I will do it when I get home from work though. :smile:

**Comment by kyrias** [comment]
@HalosGhost And yes, lables are fun.

**Comment by Narrat** [comment]
Nice to read. :)

But something else. Didn't notice it because I have clang installed by default, but if I read the CMakeLists right, clang is the default compiler with no fallback to gcc?
So clang should be added to makedepends too, as it isn't part of base-devel?

**Comment by kyrias** [comment]
Indeed! IIRC it used to override the copiler to use gcc instead, but changed that...

**Comment by kyrias** [comment]
@Narrat Now in the AUR

**Comment by HalosGhost** [comment]
:+1:
